# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

zstyle ':omz:update' mode auto      # update automatically without asking

zstyle ':omz:update' frequency 15

plugins=(git)

source $ZSH/oh-my-zsh.sh

alias zshconfig="nano ~/.zshrc"
alias dotfiles="cd ~/Documents/dotfiles && code . && exit"
